#
# Copyright (c) 2020, 2022, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: todo-list
spec:
  cluster: ToDo-Helidon
  replicas: 1
  image: ghcr.io/coherence-community/todo-list-helidon-server:23.09
  env:
    - name: TRACING_HOST
      value: "jaeger-collector"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
  application:
    type: helidon
  coherence:
    metrics:
      enabled: true
#    persistence:
#      mode: active
#      persistentVolumeClaim:
#        storageClassName: "oci-bv"
#        accessModes:
#          - ReadWriteOnce
#        resources:
#          requests:
#            storage: 50Gi
  jvm:
    memory:
      heapSize: 1g
  ports:
    - name: grpc
      port: 1408
    - name: http
      port: 7001
      serviceMonitor:
        enabled: true
    - name: metrics
      serviceMonitor:
        enabled: true
